version: '3'
services:
  api:
    build: .
    volumes:
      - .:/goland
    ports:
      - "3000:3000"
  db:
    image: postgres
    volumes:
      - ./database/pgdata:/pgdata
    ports:
      - "5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - PGDATA=/pgdata