type Feed {
    id: ID!
    title: String!
    description: String
    selfUrl: String!
}

extend type Query {
    feeds: [Feed!]!
}

input NewFeed {
    selfUrl: String
}

extend type Mutation {
    createFeed(input: NewFeed!): Feed!
}
