// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package models

type Feed struct {
	ID          string  `json:"id"`
	Title       string  `json:"title"`
	Description *string `json:"description"`
	SelfURL     string  `json:"selfUrl"`
}

type NewFeed struct {
	SelfURL *string `json:"selfUrl"`
}

type Post struct {
	ID          string  `json:"id"`
	Title       string  `json:"title"`
	Description *string `json:"description"`
	URL         string  `json:"url"`
	Feed        *Feed   `json:"feed"`
}

type User struct {
	ID       string `json:"id"`
	Email    string `json:"email"`
	Password string `json:"password"`
}
