// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package api

type Feed struct {
	ID          string  `json:"id"`
	Title       string  `json:"title"`
	Description *string `json:"description"`
	SelfURL     string  `json:"selfUrl"`
}

type NewFeed struct {
	SelfURL *string `json:"selfUrl"`
}

type Post struct {
	ID          string  `json:"id"`
	Title       string  `json:"title"`
	Description *string `json:"description"`
	URL         string  `json:"url"`
	Feed        *Feed   `json:"feed"`
}
